//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLKS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ChiTieuPhieuThue
    {
        public string MaChiTiet { get; set; }
        public string HoTenKH { get; set; }
        public Nullable<System.DateTime> NgayBatDauThue { get; set; }
        public string CCCD { get; set; }
        public string DiaChi { get; set; }
        public string MaPhieuThue { get; set; }
    
        public virtual tbl_PhieuThuePhong tbl_PhieuThuePhong { get; set; }
    }
}
