//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLKS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ThongKe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_ThongKe()
        {
            this.tbl_ChiTietThongKe = new HashSet<tbl_ChiTietThongKe>();
        }
    
        public int MaThongKe { get; set; }
        public string TenThongKe { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public Nullable<decimal> TongThuNhap { get; set; }
        public string MaNV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ChiTietThongKe> tbl_ChiTietThongKe { get; set; }
        public virtual tbl_NhanVien tbl_NhanVien { get; set; }
    }
}
