//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLKS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ChiTietPhong
    {
        public string MaPhong { get; set; }
        public string MaLoaiPhong { get; set; }
        public string TienIch { get; set; }
        public string HinhAnh { get; set; }
    
        public virtual tbl_LoaiPhong tbl_LoaiPhong { get; set; }
        public virtual tbl_Phong tbl_Phong { get; set; }
    }
}
