//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLKS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DichVuDaDat
    {
        public string ID { get; set; }
        public Nullable<System.DateTime> NgaySuDungDV { get; set; }
        public string MaHD { get; set; }
        public string MaTrangThaiDV { get; set; }
        public string MaNV { get; set; }
        public string MaKH { get; set; }
        public string MaDV { get; set; }
    
        public virtual tbl_DichVu tbl_DichVu { get; set; }
        public virtual tbl_TrangThaiDichVu tbl_TrangThaiDichVu { get; set; }
        public virtual tbl_HoaDon tbl_HoaDon { get; set; }
        public virtual tbl_KhachHang tbl_KhachHang { get; set; }
        public virtual tbl_NhanVien tbl_NhanVien { get; set; }
    }
}
